name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Skip tests and linting for cost savings (personal project)
      # Uncomment if you want quality checks:
      # - name: Install dev dependencies
      #   run: npm ci
      # - name: Run tests
      #   run: npm test
      # - name: Run linting
      #   run: npm run lint

      # Install only what's needed for deployment
      - name: Install deployment dependencies
        run: |
          # Don't install anything - aws-sdk is in Lambda runtime
          # npm ci --only=production  # Skip this line
          npm install -g serverless@3.38.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Single command deployment - that's it!
      - name: Deploy to Production
        run: serverless deploy --verbose

      # Optional: Quick smoke test
      - name: Test deployment
        run: |
          # Test the function exists
          aws lambda get-function --function-name jira-processor-v2 >/dev/null
          echo "✅ Deployment successful!"